name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: yarn 
      - name: Run Compile
        run: yarn compile
      - name: Run tests
        run: yarn test