name: Test Contract
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Contract-GitHub-Actions:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      - uses: vishnudxb/cancel-workflow@v1.2
      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install Package
        run: yarn
      # - name: Run Compile
      #   run: npx hardhat compile
      - name: Run solhint check
        run: yarn lint
      # - name: Run tests
        # run: yarn test

  Contract-GitHub-Actions-2:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
        needs:
            - Contract-GitHub-Actions
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      - uses: vishnudxb/cancel-workflow@v1.2
      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install Package
        run: yarn
      # - name: Run Compile
      #   run: npx hardhat compile
      # - name: Run solhint check
      #   run: yarn lint
      - name: Run tests
        run: yarn test
  
  Third-and-final-job:
        runs-on: ubuntu-latest
        needs: [Contract-GitHub-Actions, Contract-GitHub-Actions-2]