name: Test Contract
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Contract-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
     
      - name: Install Package
        run: yarn
      # - name: Run Compile
      #   run: npx hardhat compile
      - name: Run solhint check
        run: yarn lint
        if: ${{ failure() }}  
          steps:
            - name: Cancel current workflow run
              uses: actions/github-script@v4
              with:
                  script: |
                      github.actions.cancelWorkflowRun({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          run_id: context.runId
                      })
      # - name: Run tests
        # run: yarn test
  