name: Test Contract
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Contract-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install Package
        run: yarn
      # - name: Run Compile
      #   run: npx hardhat compile
      - name: install-globally
        run: npm i -g solhint*tgz
      - name: run-e2e-tests
        run: cd e2e && npm install && npm test
      # - name: Run solhint check
      #   run: yarn lint
      - name: Run tests
        run: yarn test
  