name: Test Contract
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Contract-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v2
      - name: Cancel current workflow run
        uses: actions/github-script@v4
        with:
          node-version: 12.x
          # script: |
          #     github.actions.cancelWorkflowRun({
          #         owner: context.repo.owner,
          #         repo: context.repo.repo,
          #         run_id: context.runId
          #     })
      - name: Install Package
        run: yarn
      # - name: Run Compile
      #   run: npx hardhat compile
      - name: Run solhint check
        run: yarn lint
      # - name: Run tests
        # run: yarn test
  